linters:
  disable-all: true
  enable:
    - dogsled
    - gofmt
    - goimports
    - gomodguard
    - goprintffuncname
    - ineffassign
    - misspell
    - nakedret
    - nestif
    - prealloc
      #- lll
      #- gomnd
      #- godox
      #- scopelint
      #- whitespace
      #- wsl
      #- dupl
      #- funlen
      #- gocognit
      #- gocyclo

  fast: false
linters-settings:
  goimports:
    local-prefixes: github.com/kapetaniosci/pipe
