apiVersion: v1
kind: Service
metadata:
  name: api
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: service
      port: 9090
      targetPort: service
    - name: admin
      port: 9085
      targetPort: admin
    - name: envoy-admin
      port: 9095
      targetPort: envoy-admin
