apiVersion: apps/v1
kind: Deployment
metadata:
  name: pipe-piped
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: piped
        image: gcr.io/kapetanios/pipecd-piped:{{ .VERSION }}
        imagePullPolicy: IfNotPresent
