args:
  useFakeAPI: true
  enableDefaultKubernetesCloudProvider: true
  projectID: your-project-id
  pipedID: your-piped-id
  pipedKey: your-piped-key

service:
  type: ClusterIP
  port: 9085

image: {}

podAnnotations: {}

nodeSelector: {}

tolerations: []

affinity: {}

# resources:
#   limits:
#     cpu: 100m
#     memory: 128Mi
#   requests:
#     cpu: 100m
#     memory: 128Mi

config: |
  apiVersion: pipecd.dev/v1beta1
  kind: Piped
  spec:
    syncInterval: 1m
    git:
      sshKeyFile: /etc/piped-secret/sshkey
      accessTokenFile: /etc/piped-secret/gittoken
    repositories:
      - repoId: pipe-debug
        remote: git@github.com:kapetaniosci/pipe-debug.git
        branch: master
      - repoId: pipe-debug-2
        remote: git@github.com:kapetaniosci/pipe-debug-2.git
        branch: dev
