apiVersion: apps/v1
kind: Deployment
metadata:
  name: pipe-runner
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: runner
        image: gcr.io/kapetanios/pipe-runner:{{ .VERSION }}
        imagePullPolicy: IfNotPresent
